kind: pipeline
type: docker # exec, ssh ,kubernetes
name: default

steps:
  - name: check
    image: golang
    pull: if-not-exists
    commands:
      - go env
      - echo -n "latest,v1.0.2,v1.0.1,v1.0.0" > .tags

  - name: build
    image: plugins/docker
    pull: if-not-exists
    privileged: true
    volumes:
    - name: dockersock
      path: /var/run/docker.sock
    environment:
      # DOCKER_HOST: "unix:///var/run/docker.sock"
      USERNAME:
        from_secret: dockeruser
      PASSWORD:
        from_secret: dockerpasswd
    settings:
      username:
        from_secret: dockeruser
      password:
        from_secret: dockerpasswd
      repo: asppj/01react-demo
      use_cache: true
      # debug: true
      insecure: true
      dry_run: true
      # registry: hub.docker.com
      dockerfile: Dockerfile
      # tags: latest
  - name: test
    image: docker:dind
    volumes:
    - name: dockersock
      path: /var/run/docker.sock
    commands:
    - sleep 5 # give docker enough time to start
    - docker ps -a

  - name: deploy
    image: plugins/docker
    pull: if-not-exists
    privileged: true
    volumes:
    - name: dockersock
      path: /var/run/docker.sock
    commands:
    - docker run -d -p 8888:80 --name web-demo --restart always

# volumes:
# - name: dockersock
#   host:
#     path: /var/run/docker.sock
# - name: dockersockdind
#   temp: {}

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersockdind
    path: /var/run
