kind: pipeline
type: docker # exec, ssh ,kubernetes
name: default

steps:
  - name: test
    image: golang
    commands:
      - go env
      - go version
      - echo -n "latest,v1.0.2,v1.0.1,v1.0.0" > .tags
  - name: build
    image: plugins/docker
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
      USERNAME:
        from_secret: dockeruser
      PASSWORD:
        from_secret: dockerpasswd
    settings:
      username:
        from_secret: dockeruser
      password:
        from_secret: dockerpasswd
      repo: hub.docker.com/asppj/01react-demo
      use_cache: true
      debug: true
      insecure: true
      dry_run: true
      registry: hub.docker.com
      dockerfile: Dockerfile
      tags: latest

