kind: pipeline
type: docker # exec, ssh ,kubernetes
name: default

steps:
  - name: greeting0
    image: alpine
    settings:
      repo: octocat/hello-world
      username:
        from_secret: password
      password:
        from_secret: password
    environment:
      USERNAME:
        from_secret: password
      PASSWORD:
        from_secret: password
    commands:
      - echo hello
      - echo world
      - echo $USERNAME
      - ls -al
  - name: build
    image: golang
    commands:
      - go env
      - go version
      - echo -n "latest,v1.0.2,v1.0.1,v1.0.0" > .tags
  - name: docker
    image: plugins/docker
    environment:
      USERNAME:
        from_secret: dockeruser
      PASSWORD:
        from_secret: dockerpasswd
    settings:
      username:
        from_secret: dockeruser
      password:
        from_secret: dockerpasswd
      mirror: https://hub.docker.com
      repo: hub.docker.com/asppj/01react-demo
      registry: hub.docker.com
      dockerfile: Dockerfile
      tags:
        - latest
        - "v1.0.2"
        - "v1.0.1"
        - "v1.0.0"
